spring:
  application:
    name: Toko Bahar
  datasource:
    url: jdbc:postgresql://localhost:5433/toko_bahar
    username: postgres
    password: 0852114477
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true
    database: postgresql
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  session:
    jdbc:
      initialize-schema: always
#  mail:
#    host: ${MAIL_HOST}
#    port: ${MAIL_PORT}
#    username: ${MAIL_USER}
#    password: ${MAIL_PASSWORD}
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#        debug: true

app:
  cors:
    allowed-origin: http://localhost:5174

server:
  port: 8081
  servlet:
    session:
      timeout: 14400
      tracking-modes: cookie
      cookie:
        http-only: true
        secure: false # Set to true in production
        same-site: strict